
/**************************************************************
 *	
 *	Bill_Jump_Sound, 8 bit, 11025Hz,
 *	1 channel, 267786 bytes/channel
 *	Total Size: 1 * 267786 + 4 (header) = 267830 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Cassie\Documents\School\4 - Spring 2017\CS 2261\Homework\M03_CassieMullins\Bill_Jump_Sound.wav
 *	Time-stamp: Thu Mar 30 15:59:44 2017
 *	
 **************************************************************/

#ifndef __BILL_JUMP_SOUNDH__
#define __BILL_JUMP_SOUNDH__

#define BILL_JUMP_SOUNDFREQ 11025
#define BILL_JUMP_SOUNDLEN 267786

extern const unsigned char Bill_Jump_Sound[267786];

#endif /* __BILL_JUMP_SOUNDH__ */
