
/**************************************************************
 *	
 *	hubMusic, 8 bit, 11025Hz,
 *	1 channel, 2831040 bytes/channel
 *	Total Size: 1 * 2831040 + 4 (header) = 2831084 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Cassie\Documents\School\4 - Spring 2017\CS 2261\Homework\M03_CassieMullins\hubMusic.wav
 *	Time-stamp: Tue Apr 04 16:10:44 2017
 *	
 **************************************************************/

#ifndef __HUBMUSICH__
#define __HUBMUSICH__

#define HUBMUSICFREQ 11025
#define HUBMUSICLEN 2831040

extern const unsigned char hubMusic[2831040];

#endif /* __HUBMUSICH__ */
