
/**************************************************************
 *	
 *	Jump, 8 bit, 11025Hz,
 *	1 channel, 8251 bytes/channel
 *	Total Size: 1 * 8251 + 4 (header) = 8295 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Cassie\Documents\School\4 - Spring 2017\CS 2261\Homework\M03_CassieMullins\Jump.wav
 *	Time-stamp: Tue Apr 04 13:59:47 2017
 *	
 **************************************************************/

#ifndef __JUMPH__
#define __JUMPH__

#define JUMPFREQ 11025
#define JUMPLEN 8251

extern const unsigned char Jump[8251];

#endif /* __JUMPH__ */
