
/**************************************************************
 *	
 *	shot, 8 bit, 11025Hz,
 *	1 channel, 10159 bytes/channel
 *	Total Size: 1 * 10159 + 4 (header) = 10203 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Cassie\Documents\School\4 - Spring 2017\CS 2261\Homework\M03_CassieMullins\shot.wav
 *	Time-stamp: Tue Apr 04 14:42:27 2017
 *	
 **************************************************************/

#ifndef __SHOTH__
#define __SHOTH__

#define SHOTFREQ 11025
#define SHOTLEN 10159

extern const unsigned char shot[10159];

#endif /* __SHOTH__ */
