
/**************************************************************
 *	
 *	splashMusic, 8 bit, 11025Hz,
 *	1 channel, 2583894 bytes/channel
 *	Total Size: 1 * 2583894 + 4 (header) = 2583938 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Cassie\Documents\School\4 - Spring 2017\CS 2261\Homework\M03_CassieMullins\splashMusic.wav
 *	Time-stamp: Mon Apr 03 22:01:36 2017
 *	
 **************************************************************/

#ifndef __SPLASHMUSICH__
#define __SPLASHMUSICH__

#define SPLASHMUSICFREQ 11025
#define SPLASHMUSICLEN 2583894

extern const unsigned char splashMusic[2583894];

#endif /* __SPLASHMUSICH__ */
