
/**************************************************************
 *	
 *	swish, 8 bit, 11025Hz,
 *	1 channel, 4866 bytes/channel
 *	Total Size: 1 * 4866 + 4 (header) = 4910 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Cassie\Documents\School\4 - Spring 2017\CS 2261\Homework\M03_CassieMullins\swish.wav
 *	Time-stamp: Tue Apr 04 13:59:40 2017
 *	
 **************************************************************/

#ifndef __SWISHH__
#define __SWISHH__

#define SWISHFREQ 11025
#define SWISHLEN 4866

extern const unsigned char swish[4866];

#endif /* __SWISHH__ */
