
/**************************************************************
 *	
 *	theme, 8 bit, 11025Hz,
 *	1 channel, 357457 bytes/channel
 *	Total Size: 1 * 357457 + 4 (header) = 357501 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Cassie\Documents\School\4 - Spring 2017\CS 2261\Homework\M03_CassieMullins\theme.wav
 *	Time-stamp: Thu Mar 30 20:44:27 2017
 *	
 **************************************************************/

#ifndef __THEMEH__
#define __THEMEH__

#define THEMEFREQ 11025
#define THEMELEN 357457

extern const unsigned char theme[357457];

#endif /* __THEMEH__ */
