
/**************************************************************
 *	
 *	train, 8 bit, 11025Hz,
 *	1 channel, 30569 bytes/channel
 *	Total Size: 1 * 30569 + 4 (header) = 30613 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Cassie\Documents\School\4 - Spring 2017\CS 2261\Homework\M04_CassieMullins\train.wav
 *	Time-stamp: Tue Apr 11 20:47:42 2017
 *	
 **************************************************************/

#ifndef __TRAINH__
#define __TRAINH__

#define TRAINFREQ 11025
#define TRAINLEN 30569

extern const unsigned char train[30569];

#endif /* __TRAINH__ */
