
/**************************************************************
 *	
 *	tvMusic, 8 bit, 11025Hz,
 *	2 channel, 2313961 bytes/channel
 *	Total Size: 2 * 2313961 + 4 (header) = 4627966 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Cassie\Documents\School\4 - Spring 2017\CS 2261\Homework\M03_CassieMullins\tvMusic.wav
 *	Time-stamp: Mon Apr 03 22:37:03 2017
 *	
 **************************************************************/

#ifndef __TVMUSICH__
#define __TVMUSICH__

#define TVMUSICFREQ 11025
#define TVMUSICLEN 2313961

extern const unsigned char tvMusic_c1[2313961];
extern const unsigned char tvMusic_c2[2313961];

#endif /* __TVMUSICH__ */
