
/**************************************************************
 *	
 *	virusMusic, 8 bit, 11025Hz,
 *	1 channel, 2261587 bytes/channel
 *	Total Size: 1 * 2261587 + 4 (header) = 2261631 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Cassie\Documents\School\4 - Spring 2017\CS 2261\Homework\M03_CassieMullins\virusMusic.wav
 *	Time-stamp: Mon Apr 03 22:01:33 2017
 *	
 **************************************************************/

#ifndef __VIRUSMUSICH__
#define __VIRUSMUSICH__

#define VIRUSMUSICFREQ 11025
#define VIRUSMUSICLEN 2261587

extern const unsigned char virusMusic[2261587];

#endif /* __VIRUSMUSICH__ */
